.swiftlint.yml, Sources/Clickstream/AWSClickstreamPlugin+ClientBehavior.swift, Sources/Clickstream/AWSClickstreamPlugin+Configure.swift, Sources/Clickstream/AWSClickstreamPlugin+Reset.swift, Sources/Clickstream/AWSClickstreamPlugin.swift, Sources/Clickstream/ClickstreamAnalytics.swift, Sources/Clickstream/ClickstreamAttribute.swift, Sources/Clickstream/ClickstreamObjc.swift, Sources/Clickstream/Configuration/AWSClickstreamPluginConfiguration.swift, Sources/Clickstream/Dependency/Clickstream/ClickstreamContext.swift, Sources/Clickstream/Dependency/Clickstream/Event/Event.swift, Sources/Clickstream/PackageInfo.swift, Sources/Clickstream/Support/Utils/ClickstreamLogger.swift, Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift, Tests/ClickstreamTests/Clickstream/SessionClientTests.swift, Tests/ClickstreamTests/ClickstreamAnalyticsTest.swift, Tests/ClickstreamTests/IntegrationTest.swift
1. add api for objective-c 
2. add test case for ClickstreamObjc
3. change class and method visibility for api doc generate
4. update version to 0.4.1
=> feat: add Swift-Objective C interoperability

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/PULL_REQUEST_TEMPLATE.md
=> chore: add issue and pr template

.github/workflows/jzaay_doc_gen.yml, .jazzy.yaml, README.md, Sources/Clickstream/ClickstreamAttribute.swift, Sources/Clickstream/Dependency/Clickstream/ActivityTracking/UIViewController+Swizzle.swift, Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift, Sources/Clickstream/Support/Utils/UserDefaultsUtil.swift
1. fix swift build issue.
2. add action to publish API doc.
=> chore: add action to publish API doc

README.md
1. add Objective-C api Reference in readme
=> docs: add Objective-C api Reference in readme

README.md
update readme for introduction
=> chore: update readme for introduction

Sources/Clickstream/Dependency/Clickstream/System/SystemInfo.swift, Sources/Clickstream/PackageInfo.swift, Tests/ClickstreamTests/Clickstream/SystemInfoTest.swift
1. add model parser for iOS device
=> feat: add iOS model parser

README.md, Sources/Clickstream/ClickstreamObjc.swift, Tests/ClickstreamTests/IntegrationTest.swift
1. update doc for SDK api change.
=> chore: update doc for api change

README.md
1. add solution link in readme.
=> chore: add solution link in readme

Sources/Clickstream/Network/NetworkMonitor.swift, Sources/Clickstream/PackageInfo.swift
Fix NWPath thread safety issue, referrer to the the known issues： https://developer.apple.com/forums/thread/133112
Passed the Device Farm test, covering a total of 32 models from iPhone 6s to iPhone 14, iOS versions covering 13 14 15 16, a total of about 15 hours of Fuzz testing, all tests are passed.
=> fix: nwpath thread safety issue

.github/workflows/release.yml, release.sh
1. Add release new version action
=> ci: add release new version action

Sources/Clickstream/DataBase/ClickstreamDBUtil.swift, Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift, Sources/Clickstream/Dependency/Clickstream/Event/Event.swift, Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift, Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
=> feat: add app end preset event

Sources/Clickstream/AWSClickstreamPlugin+Configure.swift, Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift, Tests/ClickstreamTests/Clickstream/SessionClientTests.swift, Tests/ClickstreamTests/IntegrationTest.swift
fix: session start crash issue
=> fix: session start crash issue

Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift, Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift, Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
1. change the screen unique id generation method
=> fix: change the screen unique id generation method

Sources/Clickstream/Dependency/Clickstream/Analytics/AnalyticsClient.swift, Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift, Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift, Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift, Tests/ClickstreamTests/Clickstream/SessionClientTests.swift, Tests/ClickstreamTests/Mock/MockEventRecorder.swift
1. add `_screen_name` and `_screen_unique_id` as preset attributes
=> feat: add preset attributes screen name and screen unique id

.github/workflows/title-lint.yml
1. update pr title lint action
=> ci: update pr title lint action

README.md
1. add custom item attribute in readme
=> chore: add custom item attribute in readme

.github/workflows/title-lint.yml
1. add release in pr title lint
=> ci: add release in pr title lint

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.10.0
=> release: clickstream Swift 0.10.0

IntegrationTest/devicefarm/logcat_test.py, Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift, Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift, Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
1. add screen view event after session start
=> feat: add screen view event after session start

Sources/Clickstream/AWSClickstreamPlugin+Configure.swift, Sources/Clickstream/Dependency/Clickstream/Analytics/AnalyticsClient.swift, Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift, Sources/Clickstream/Dependency/Clickstream/Session/Session.swift, Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift, Tests/ClickstreamTests/Clickstream/AnalyticsClientTest.swift, Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift, Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift, Tests/ClickstreamTests/Clickstream/SessionClientTests.swift, Tests/ClickstreamTests/ClickstreamPluginTestBase.swift, Tests/ClickstreamTests/IntegrationTest.swift
1. fix the sessionId in first open and session start event
2. optimize session initialization
=> fix: sessionId in first open and session start events

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.10.1
=> release: clickstream Swift 0.10.1

.github/workflows/tag_and_release.yml
1. make release tag name consistent with git tag
=> fix: make release tag name consistent with git tag

Sources/Clickstream/Network/NetRequest.swift, Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
1. support calibrate local timestamp
=> feat: support calibrate local timestamp

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.11.0
=> release: clickstream Swift 0.11.0

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.12.0
=> release: clickstream Swift 0.12.0

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.12.1
=> release: clickstream Swift 0.12.1

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.12.2
=> release: clickstream Swift 0.12.2

IntegrationTest/requirements.txt
1. bump python requests version
=> chore: bump python requests version

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.12.3
=> release: clickstream Swift 0.12.3

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.12.4
=> release: clickstream Swift 0.12.4

Sources/Clickstream/PackageInfo.swift
1. release: clickstream Swift 0.12.5
=> release: clickstream Swift 0.12.5
