- .github/workflows/jazzy_build.yml
- .github/workflows/jazzy_doc_gen.yml
- .jazzy.yaml
closes #8 
fix the jazzy_doc_gen action fail. 
test [jazzy doc gen action](https://github.com/awslabs/clickstream-swift/actions/runs/5075163163) passed.
test [pages build and publish action](https://github.com/awslabs/clickstream-swift/actions/runs/5075187982) passed.
> fix: jazzy doc generate fail

- README.md
- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Sources/Clickstream/Dependency/Clickstream/ClickstreamContext.swift
- Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
Fixed Gitlab issue [#423](https://gitlab.aws.dev/aws-gcr-solutions/incubator/web-analytics-on-aws/clickstream-analytics-on-aws/-/issues/423)
1. Fix the configuration for disable record screen view event is not work.
2. Add integrate step for SwiftUI project in readme.
> fix: disable record screenview event if it's no enabled

- Sources/Clickstream/AWSClickstreamPlugin+ClientBehavior.swift
- Sources/Clickstream/ClickstreamAnalytics.swift
- Sources/Clickstream/ClickstreamObjc.swift
- Sources/Clickstream/PackageInfo.swift
- Tests/ClickstreamTests/IntegrationTest.swift
The timestamp of set_timestamp_micros in the user_properties is later than the event_timestamp
1. Fixed the time order in event and user attributes.
2. Simplify the SDK api.
> fix: timestamp order in event and user attributes.

- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Sources/Clickstream/Dependency/Clickstream/Event/Event.swift
- Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift
- Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
- Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. add _app_start event
2. change user engagement attribute in screen_view
> feat: add _app_start event, change user engagement attribute

- README.md
- Sources/Clickstream/AWSClickstreamPlugin+ClientBehavior.swift
- Sources/Clickstream/Dependency/Clickstream/Analytics/AnalyticsClient.swift
- Sources/Clickstream/Dependency/Clickstream/Analytics/EventRecorder.swift
- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/IntegrationTest.swift
- Tests/ClickstreamTests/Mock/MockAnalyticsClient.swift
- Tests/ClickstreamTests/Mock/MockEventRecorder.swift
1. add background task for sending request when app move to background.
2. change event log to prettier format.
> feat: support sending events when app move to background

- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift
- Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
1. update screen start timestamp when app enter foreground.
> fix: update screen start timestamp when app enter foreground

- Sources/Clickstream/AWSClickstreamPlugin+ClientBehavior.swift
- Sources/Clickstream/Dependency/Clickstream/Analytics/AnalyticsClient.swift
- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift
- Sources/Clickstream/Dependency/Clickstream/Event/Event.swift
- Tests/ClickstreamTests/Clickstream/AnalyticsClientTest.swift
- Tests/ClickstreamTests/Clickstream/ClickstreamEventTest.swift
- Tests/ClickstreamTests/ClickstreamPluginBehaviorTest.swift
- Tests/ClickstreamTests/EventTest.swift
- Tests/ClickstreamTests/Mock/MockAnalyticsClient.swift
1. add error codes consistent with Web SDK
2. add _clickstream_error preset event, when event name, global/user attribute is invalid.
> feat: add error code and clickstream error event

- Sources/Clickstream/Dependency/Clickstream/Analytics/AnalyticsClient.swift
- Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift
- Sources/Clickstream/Support/Extension/String+HashCode.swift
- Tests/ClickstreamTests/Clickstream/ClickstreamEventTest.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
1. change event hash code calculation method to sha256
> feat: change event hash code calculation method to sha256

- Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift
- Sources/Clickstream/Network/NetRequest.swift
- Tests/ClickstreamTests/Clickstream/AnalyticsClientTest.swift
- Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
1. remove hash code in event attribute
2. add hash code in request query parameter
> feat: add hash code to request query parameter

- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
1. remove `_engagement_time_msec` in first screen view event
2. optimize getting the `_previous_timestamp` value in first screen view event
> fix: optimize engagement time and previous timestamp attribute in first screen view

- README.md
- Sources/Clickstream/AWSClickstreamPlugin+ClientBehavior.swift
- Sources/Clickstream/ClickstreamAnalytics.swift
- Sources/Clickstream/ClickstreamObjc.swift
- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Sources/Clickstream/Dependency/Clickstream/ClickstreamContext.swift
- Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift
- Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
- Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
- Tests/ClickstreamTests/ClickstreamPluginBehaviorTest.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. support enable and disable sdk
> feat: support enable and disable sdk

- Sources/Clickstream/ClickstreamAnalytics.swift
- Sources/Clickstream/Dependency/Clickstream/Analytics/EventRecorder.swift
- Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift
- Sources/Clickstream/Support/Extension/JsonObject+ToJsonString.swift
- Tests/ClickstreamTests/Clickstream/ClickstreamEventTest.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/DataBase/ClickstreamDBUtilTest.swift
1. support log items
2. change item attribute visibility and add document
> chore: support log item attributes and change visibility for item attribute

- Sources/Clickstream/Dependency/Clickstream/Event/EventChecker.swift
- Tests/ClickstreamTests/Clickstream/ClickstreamEventTest.swift
1. fixed the issue that the total number of item attributes is limited to 10
> fix: the total number of item attributes is limited to 10

- Sources/Clickstream/ClickstreamObjc.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. add ClickstreamItemKey for Objective-C API
> fix: add items key for objc

- .github/workflows/integration_test.yml
- Sources/Clickstream/AWSClickstreamPlugin+Configure.swift
- Sources/Clickstream/ClickstreamObjc.swift
- Sources/Clickstream/Dependency/Clickstream/AutoRecord/AutoRecordEventClient.swift
- Sources/Clickstream/Dependency/Clickstream/Session/SessionClient.swift
- Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. support lazy initialization of the SDK
> feat: support lazy initialization of the SDK

- .github/workflows/test.yml
- README.md
- Sources/Clickstream/ClickstreamAnalytics.swift
- Sources/Clickstream/ClickstreamObjc.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. add preset traffic source attributes
2. add `_app_install_channel`, event `_value` and `_currency` preset attributes
> feat: add preset traffic source attributes

- README.md
- Sources/Clickstream/ClickstreamObjc.swift
- Sources/Clickstream/Dependency/Clickstream/ClickstreamContext.swift
- Tests/ClickstreamTests/Clickstream/AnalyticsClientTest.swift
- Tests/ClickstreamTests/Clickstream/AutoRecordEventClientTest.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/Clickstream/SessionClientTests.swift
- Tests/ClickstreamTests/ClickstreamPluginTestBase.swift
- Tests/ClickstreamTests/DataBase/ClickstreamDBUtilTest.swift
- Tests/ClickstreamTests/IntegrationTest.swift
- Tests/ClickstreamTests/SDKInitialTest.swift
1. support add global attributes when using Objc api
2. fix test issues
> feat: support add global attributes when using Objc api

- Sources/Clickstream/Dependency/Clickstream/ClickstreamContext.swift
- Sources/Clickstream/Dependency/Clickstream/Event/Event.swift
- Sources/Clickstream/Dependency/Clickstream/Event/EventChecker.swift
- Tests/ClickstreamTests/Clickstream/ClickstreamEventTest.swift
- Tests/ClickstreamTests/EventCheckerTest.swift
1. fix the issue with converting non-finite values to JSON string
> fix: crash when converting infinite values to JSON string

- Sources/Clickstream/Dependency/Clickstream/Analytics/EventRecorder.swift
- Sources/Clickstream/Support/Extension/JsonObject+ToJsonString.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/Util/ToJsonStringUtilTest.swift
1. fix crash when converting invalid JSON object
> fix: crash when converting invalid JSON object

- IntegrationTest/devicefarm/logcat_test.py
- Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. fix crash when user attribute is empty
> fix: crash when user attribute is empty

- .swiftformat
- .swiftlint.yml
- Sources/Clickstream/AWSClickstreamPlugin+ClientBehavior.swift
- Sources/Clickstream/Dependency/Clickstream/Analytics/AnalyticsClient.swift
- Sources/Clickstream/Dependency/Clickstream/Event/ClickstreamEvent.swift
- Tests/ClickstreamTests/Clickstream/ClickstreamEventTest.swift
- Tests/ClickstreamTests/Clickstream/EventRecorderTest.swift
- Tests/ClickstreamTests/IntegrationTest.swift
1. attributes thread safety issue
> fix: attributes thread safety issue
